/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailme;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class MainApp extends javax.swing.JFrame {


    public User user;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    public MainApp(User user) {
        initComponents();
        this.user = user;
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        setVisible(true);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabPane = new javax.swing.JTabbedPane();
        inboxPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inboxScrollPane1 = new javax.swing.JScrollPane();
        inboxTable1 = new javax.swing.JTable();
        outboxPanel = new javax.swing.JPanel();
        outboxScrollPane1 = new javax.swing.JScrollPane();
        outboxTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sendPanel = new javax.swing.JPanel();
        penerimaTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesanTextArea1 = new javax.swing.JTextArea();
        kirimButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        penerimaLabel = new javax.swing.JLabel();
        pesanLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("user");

        inboxPanel.setLayout(null);

        jLabel1.setText("Kotak Masuk");
        inboxPanel.add(jLabel1);
        jLabel1.setBounds(169, 13, 80, 16);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        inboxScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        inboxTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Pengirim", "Pesan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inboxScrollPane1.setViewportView(inboxTable1);

        jPanel2.add(inboxScrollPane1);
        inboxScrollPane1.setBounds(10, 60, 390, 220);

        inboxPanel.add(jPanel2);
        jPanel2.setBounds(0, -20, 420, 300);

        MainTabPane.addTab("Inbox", inboxPanel);

        outboxPanel.setBackground(new java.awt.Color(204, 255, 204));
        outboxPanel.setLayout(null);

        outboxTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Penerima", "Pesan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outboxScrollPane1.setViewportView(outboxTable1);

        outboxPanel.add(outboxScrollPane1);
        outboxScrollPane1.setBounds(12, 42, 390, 229);

        jLabel2.setText("Kotak Keluar");
        outboxPanel.add(jLabel2);
        jLabel2.setBounds(178, 13, 80, 16);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        outboxPanel.add(jPanel3);
        jPanel3.setBounds(60, 160, 100, 100);

        MainTabPane.addTab("Outbox", outboxPanel);

        sendPanel.setLayout(null);
        sendPanel.add(penerimaTextField1);
        penerimaTextField1.setBounds(135, 48, 93, 22);

        pesanTextArea1.setColumns(20);
        pesanTextArea1.setRows(5);
        jScrollPane1.setViewportView(pesanTextArea1);

        sendPanel.add(jScrollPane1);
        jScrollPane1.setBounds(135, 93, 226, 86);

        kirimButton.setText("Kirim");
        kirimButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kirimButtonMouseClicked(evt);
            }
        });
        sendPanel.add(kirimButton);
        kirimButton.setBounds(300, 209, 70, 25);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        penerimaLabel.setText("Penerima");

        pesanLabel.setText("Pesan");

        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penerimaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(penerimaLabel)
                .addGap(18, 18, 18)
                .addComponent(pesanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );

        sendPanel.add(jPanel1);
        jPanel1.setBounds(0, -30, 420, 320);

        MainTabPane.addTab("Send Message", sendPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kirimButtonMouseClicked
        // TODO add your handling code here:
        String penerima = penerimaTextField1.getText();
        String pesan = pesanTextArea1.getText();
        String pengirim = user.getNama();
        if(penerimaTextField1.getText() != null && pesanTextArea1.getText() != null){
            try{
                sql = "INSERT into pesan(namapengirim, namapenerima, pesan) VALUES (" + "'" +pengirim+ "'"
                        + "" + "," + "'" +penerima+ "'" + "," + "'" +pesan+ "'"+")";
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Pesan Berhasil di Kirim");
                loadData();
                penerimaTextField1.setText(null);
                pesanTextArea1.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else{
                JOptionPane.showMessageDialog(this, "Semua field harus di isi");
        }
        
        
    }//GEN-LAST:event_kirimButtonMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Yakin ingin keluar ?");
        this.dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainApp().setVisible(true);
//            }
//        });
//    }
    public void loadData(){
        DefaultTableModel modelInbox = (DefaultTableModel)inboxTable1.getModel();
        DefaultTableModel modelOutbox = (DefaultTableModel)outboxTable1.getModel();
        try {
                sql = "SELECT * FROM pesan WHERE namapenerima="+"'"+user.getNama()+"'";
                rs = stat.executeQuery(sql);
                modelInbox.setRowCount(0);
                while(rs.next()){                    
                    modelInbox.addRow(new Object[]{rs.getInt("id"),rs.getString("namapengirim"),rs.getString("pesan")});
                }
                
                sql = "SELECT * FROM pesan WHERE namapengirim="+"'"+user.getNama()+"'";
                rs = stat.executeQuery(sql);
                modelOutbox.setRowCount(0);
                while(rs.next()){                    
                    modelOutbox.addRow(new Object[]{rs.getInt("id"),rs.getString("namapenerima"),rs.getString("pesan")});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabPane;
    private javax.swing.JPanel inboxPanel;
    private javax.swing.JScrollPane inboxScrollPane1;
    private javax.swing.JTable inboxTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JPanel outboxPanel;
    private javax.swing.JScrollPane outboxScrollPane1;
    private javax.swing.JTable outboxTable1;
    private javax.swing.JLabel penerimaLabel;
    private javax.swing.JTextField penerimaTextField1;
    private javax.swing.JLabel pesanLabel;
    private javax.swing.JTextArea pesanTextArea1;
    private javax.swing.JPanel sendPanel;
    // End of variables declaration//GEN-END:variables
}
